// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Prisma 7: CLI (migrate, studio) uses `url` here — must be the direct/session connection.
  // Runtime app queries use DATABASE_URL (pooled) via lib/db.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
