import { AvailabilityConsultationType } from "../../generated/prisma/client.js";

export type DoctorCatalogEntry = {
  name: string;
  specialization: string;
  phone: string;
  qualification: string;
  yearsExperience: number;
  bio: string;
  timezone: string;
  currency: string;
  consultationType: AvailabilityConsultationType;
  price30Cents: number;
};

export const DOCTOR_CATALOG: DoctorCatalogEntry[] = [
  {
    name: "Dr. Aisha Mehta",
    specialization: "Cardiologist",
    phone: "+15550101001",
    qualification: "MBBS, MD (Cardiology)",
    yearsExperience: 14,
    bio: "Focused on preventive cardiology, hypertension, and chest pain evaluation.",
    timezone: "America/New_York",
    currency: "USD",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 6000,
  },
  {
    name: "Dr. Liam Carter",
    specialization: "Neurologist",
    phone: "+15550101002",
    qualification: "MD, DM (Neurology)",
    yearsExperience: 11,
    bio: "Treats migraines, seizures, nerve pain, dizziness, and memory concerns.",
    timezone: "America/New_York",
    currency: "USD",
    consultationType: AvailabilityConsultationType.ONLINE,
    price30Cents: 6500,
  },
  {
    name: "Dr. Sofia Rossi",
    specialization: "Dermatologist",
    phone: "+15550101003",
    qualification: "MD (Dermatology)",
    yearsExperience: 9,
    bio: "Specializes in acne, rashes, hair loss, mole checks, and chronic skin irritation.",
    timezone: "Europe/Paris",
    currency: "EUR",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 5500,
  },
  {
    name: "Dr. Noah Williams",
    specialization: "General Physician",
    phone: "+15550101004",
    qualification: "MD",
    yearsExperience: 8,
    bio: "Provides primary care for fever, fatigue, respiratory illness, and preventive visits.",
    timezone: "America/Toronto",
    currency: "CAD",
    consultationType: AvailabilityConsultationType.ONLINE,
    price30Cents: 3500,
  },
  {
    name: "Dr. Priya Nair",
    specialization: "Gynecologist",
    phone: "+15550101005",
    qualification: "MBBS, MS (OBGYN)",
    yearsExperience: 13,
    bio: "Supports menstrual health, pelvic pain, contraception counseling, and wellness visits.",
    timezone: "Asia/Kolkata",
    currency: "INR",
    consultationType: AvailabilityConsultationType.CLINIC,
    price30Cents: 300000,
  },
  {
    name: "Dr. Ethan Brooks",
    specialization: "Pediatrician",
    phone: "+15550101006",
    qualification: "MD (Pediatrics)",
    yearsExperience: 10,
    bio: "Child health visits for fever, cough, growth checks, vaccinations, and nutrition.",
    timezone: "America/Chicago",
    currency: "USD",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 4500,
  },
  {
    name: "Dr. Maya Chen",
    specialization: "ENT (Otolaryngologist)",
    phone: "+15550101007",
    qualification: "MS (ENT)",
    yearsExperience: 12,
    bio: "Treats ear pain, sinus symptoms, hearing issues, sore throat, and voice changes.",
    timezone: "Asia/Singapore",
    currency: "SGD",
    consultationType: AvailabilityConsultationType.CLINIC,
    price30Cents: 7000,
  },
  {
    name: "Dr. Omar Khalid",
    specialization: "Pulmonologist",
    phone: "+15550101008",
    qualification: "MD (Pulmonology)",
    yearsExperience: 15,
    bio: "Focused on asthma, chronic cough, breathlessness, wheezing, and sleep breathing issues.",
    timezone: "Asia/Dubai",
    currency: "AED",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 55000,
  },
  {
    name: "Dr. Emma Taylor",
    specialization: "Endocrinologist",
    phone: "+15550101009",
    qualification: "MD (Endocrinology)",
    yearsExperience: 12,
    bio: "Diabetes, thyroid, hormonal disorders, metabolic health, and weight concerns.",
    timezone: "Europe/London",
    currency: "GBP",
    consultationType: AvailabilityConsultationType.ONLINE,
    price30Cents: 7000,
  },
  {
    name: "Dr. Lucas Martin",
    specialization: "Orthopedic Surgeon",
    phone: "+15550101010",
    qualification: "MS (Orthopedics)",
    yearsExperience: 16,
    bio: "Evaluates joint pain, sports injuries, fractures, and spine-related orthopedic concerns.",
    timezone: "Europe/Paris",
    currency: "EUR",
    consultationType: AvailabilityConsultationType.CLINIC,
    price30Cents: 8000,
  },
  {
    name: "Dr. Hannah Kim",
    specialization: "Psychiatrist",
    phone: "+15550101011",
    qualification: "MD (Psychiatry)",
    yearsExperience: 10,
    bio: "Supports anxiety, depression, sleep issues, stress, and medication management.",
    timezone: "America/Los_Angeles",
    currency: "USD",
    consultationType: AvailabilityConsultationType.ONLINE,
    price30Cents: 7500,
  },
  {
    name: "Dr. Daniel Green",
    specialization: "Gastroenterologist",
    phone: "+15550101012",
    qualification: "MD, DM (Gastroenterology)",
    yearsExperience: 14,
    bio: "Treats reflux, abdominal pain, bowel changes, liver concerns, and digestive symptoms.",
    timezone: "America/New_York",
    currency: "USD",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 6800,
  },
  {
    name: "Dr. Fatima Rahman",
    specialization: "Ophthalmologist",
    phone: "+15550101013",
    qualification: "MS (Ophthalmology)",
    yearsExperience: 11,
    bio: "Eye care for redness, blurred vision, eye pain, cataracts, and diabetic eye screening.",
    timezone: "Asia/Dubai",
    currency: "AED",
    consultationType: AvailabilityConsultationType.CLINIC,
    price30Cents: 50000,
  },
  {
    name: "Dr. Arjun Kapoor",
    specialization: "Urologist",
    phone: "+15550101014",
    qualification: "MS, MCh (Urology)",
    yearsExperience: 13,
    bio: "Kidney stones, urinary symptoms, prostate health, and male reproductive concerns.",
    timezone: "Asia/Kolkata",
    currency: "INR",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 350000,
  },
  {
    name: "Dr. Olivia Brown",
    specialization: "Rheumatologist",
    phone: "+15550101015",
    qualification: "MD (Rheumatology)",
    yearsExperience: 9,
    bio: "Joint stiffness, inflammatory arthritis, lupus, autoimmune symptoms, and chronic pain.",
    timezone: "Australia/Sydney",
    currency: "AUD",
    consultationType: AvailabilityConsultationType.ONLINE,
    price30Cents: 8500,
  },
  {
    name: "Dr. James Wilson",
    specialization: "Nephrologist",
    phone: "+15550101016",
    qualification: "MD, DM (Nephrology)",
    yearsExperience: 12,
    bio: "Chronic kidney disease, electrolyte disorders, dialysis planning, and hypertension related to renal health.",
    timezone: "America/Chicago",
    currency: "USD",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 7200,
  },
  {
    name: "Dr. Isabel Torres",
    specialization: "Allergist & Immunologist",
    phone: "+15550101017",
    qualification: "MD (Allergy & Immunology)",
    yearsExperience: 10,
    bio: "Seasonal allergies, asthma triggers, food sensitivities, and immunotherapy planning.",
    timezone: "America/Denver",
    currency: "USD",
    consultationType: AvailabilityConsultationType.CLINIC,
    price30Cents: 5200,
  },
  {
    name: "Dr. Viktor Petrov",
    specialization: "Medical Oncologist",
    phone: "+15550101018",
    qualification: "MD, PhD (Oncology)",
    yearsExperience: 17,
    bio: "Coordinates cancer care plans, treatment side-effect management, and survivorship follow-up.",
    timezone: "Europe/Berlin",
    currency: "EUR",
    consultationType: AvailabilityConsultationType.BOTH,
    price30Cents: 9500,
  },
  {
    name: "Dr. Yuki Tanaka",
    specialization: "Infectious Disease Specialist",
    phone: "+15550101019",
    qualification: "MD (Infectious Diseases)",
    yearsExperience: 11,
    bio: "Complex infections, travel medicine, antibiotic stewardship, and post-hospital follow-up.",
    timezone: "Asia/Tokyo",
    currency: "JPY",
    consultationType: AvailabilityConsultationType.ONLINE,
    price30Cents: 900000,
  },
];
